module.exports = {
  'camelcase': [
    2,
    {
      properties: 'never',
    },
  ],
  'capitalized-comments': [
    2,
    'always',
    {
      ignoreConsecutiveComments: true,
    },
  ],
  'constructor-super': 2,
  'default-case-last': 2,
  'eqeqeq': [
    2,
    'always',
    {
      null: 'ignore',
    },
  ],
  'func-style': 2,
  'getter-return': 2,
  'grouped-accessor-pairs': [2, 'getBeforeSet'],
  'handle-callback-err': 2,
  'line-comment-position': [
    2,
    {
      position: 'above',
    },
  ],
  'new-cap': [
    2,
    {
      properties: false,
    },
  ],
  'no-array-constructor': 2,
  'no-async-promise-executor': 2,
  'no-caller': 2,
  'no-class-assign': 2,
  'no-compare-neg-zero': 2,
  'no-cond-assign': [2, 'always'],
  'no-const-assign': 2,
  'no-constant-condition': 2,
  'no-constructor-return': 2,
  'no-delete-var': 2,
  'no-dupe-args': 2,
  'no-dupe-else-if': 2,
  'no-dupe-keys': 2,
  'no-duplicate-case': 2,
  'no-empty': [
    2,
    {
      allowEmptyCatch: true,
    },
  ],
  'no-empty-character-class': 2,
  'no-empty-static-block': 2,
  'no-eval': 2,
  'no-extend-native': 2,
  'no-extra-boolean-cast': 2,
  'no-fallthrough': 2,
  'no-func-assign': 2,
  'no-global-assign': 2,
  'no-implicit-coercion': 2,
  'no-implied-eval': 2,
  'no-invalid-regexp': 2,
  'no-irregular-whitespace': 2,
  'no-labels': 2,
  'no-lone-blocks': 2,
  'no-lonely-if': 2,
  'no-misleading-character-class': 2,
  'no-multi-str': 2,
  'no-nested-ternary': 2,
  'no-new-native-nonconstructor': 2,
  'no-new-object': 2,
  'no-new-require': 2,
  'no-new-wrappers': 2,
  'no-obj-calls': 2,
  'no-octal': 2,
  'no-path-concat': 2,
  'no-proto': 2,
  'no-redeclare': 2,
  'no-return-await': 2,
  'no-script-url': 2,
  'no-self-compare': 2,
  'no-sequences': 2,
  'no-this-before-super': 2,
  'no-undef': 2,
  'no-undef-init': 2,
  'no-unneeded-ternary': 2,
  'no-unreachable': 2,
  'no-unsafe-negation': 2,
  'no-unsafe-optional-chaining': 2,
  'no-unused-vars': [
    2,
    {
      varsIgnorePattern: '^h$|^React$',
    },
  ],
  'no-useless-call': 2,
  'no-useless-catch': 2,
  'no-var': 2,
  'no-void': 2,
  'one-var': [2, 'never'],
  'prefer-const': 2,
  'require-await': 2,
  'spaced-comment': [2, 'always'],
  'use-isnan': 2,
  'valid-jsdoc': [
    2,
    {
      prefer: {
        return: 'returns',
      },
      requireParamDescription: false,
      requireReturn: false,
      requireReturnDescription: false,
    },
  ],
  'valid-typeof': 2,
}
