module.exports = {
	'array-bracket-spacing': [ 2, 'always', {
		arraysInArrays: false,
		objectsInArrays: false,
	}],
	'arrow-parens': [ 2, 'always' ],
	'arrow-spacing': [ 2, {
		after: true,
		before: true,
	}],
	'brace-style': [ 2, '1tbs', {
		allowSingleLine: true,
	}],
	'callback-return': 2,
	'camelcase': [ 2, {
		properties: 'never',
	}],
	'comma-dangle': [ 2, {
		arrays: 'always-multiline',
		exports: 'always-multiline',
		functions: 'always-multiline',
		imports: 'always-multiline',
		objects: 'always-multiline',
	}],
	'comma-spacing': [ 2, {
		after: true,
		before: false,
	}],
	'comma-style': [ 2, 'last' ],
	'computed-property-spacing': 2,
	'constructor-super': 2,
	'default-case-last': 2,
	'dot-location': [ 2, 'property' ],
	'eol-last': [ 2, 'never' ],
	'eqeqeq': [ 2, 'always', {
		null: 'ignore',
	}],
	'func-call-spacing': 2,
	'func-style': 2,
	'generator-star-spacing': [ 2, {
		before: false,
	}],
	'getter-return': 2,
	'grouped-accessor-pairs': [ 2, 'getBeforeSet' ],
	'handle-callback-err': 2,
	'implicit-arrow-linebreak': 2,
	'indent': [ 2, 'tab', {
		CallExpression: {
			arguments: 'off',
		},
		SwitchCase: 1,
	}],
	'jsx-quotes': [ 2, 'prefer-double' ],
	'key-spacing': [ 2, {
		afterColon: true,
		beforeColon: false,
	}],
	'keyword-spacing': 2,
	'lines-between-class-members': [ 2, 'always', {
		exceptAfterSingleLine: true,
	}],
	'new-cap': 2,
	'new-parens': 2,
	'newline-per-chained-call': 2,
	'no-array-constructor': 2,
	'no-async-promise-executor': 2,
	'no-caller': 2,
	'no-class-assign': 2,
	'no-compare-neg-zero': 2,
	'no-cond-assign': [ 2, 'always' ],
	'no-const-assign': 2,
	'no-constant-condition': 2,
	'no-constructor-return': 2,
	'no-delete-var': 2,
	'no-dupe-args': 2,
	'no-dupe-else-if': 2,
	'no-dupe-keys': 2,
	'no-duplicate-case': 2,
	'no-empty': [ 2, {
		allowEmptyCatch: true,
	}],
	'no-empty-character-class': 2,
	'no-eval': 2,
	'no-extend-native': 2,
	'no-extra-boolean-cast': 2,
	'no-extra-parens': [ 2, 'functions' ],
	'no-extra-semi': 2,
	'no-fallthrough': 2,
	'no-floating-decimal': 2,
	'no-func-assign': 2,
	'no-global-assign': 2,
	'no-implicit-coercion': 2,
	'no-implied-eval': 2,
	'no-invalid-regexp': 2,
	'no-irregular-whitespace': 2,
	'no-labels': 2,
	'no-lone-blocks': 2,
	'no-lonely-if': 2,
	'no-misleading-character-class': 2,
	'no-mixed-spaces-and-tabs': 2,
	'no-multi-spaces': 2,
	'no-multi-str': 2,
	'no-multiple-empty-lines': 2,
	'no-nested-ternary': 2,
	'no-new-func': 2,
	'no-new-object': 2,
	'no-new-require': 2,
	'no-new-wrappers': 2,
	'no-obj-calls': 2,
	'no-octal': 2,
	'no-path-concat': 2,
	'no-proto': 2,
	'no-redeclare': 2,
	'no-script-url': 2,
	'no-self-compare': 2,
	'no-sequences': 2,
	'no-this-before-super': 2,
	'no-trailing-spaces': 2,
	'no-undef': 2,
	'no-undef-init': 2,
	'no-unexpected-multiline': 2,
	'no-unneeded-ternary': 2,
	'no-unreachable': 2,
	'no-unsafe-negation': 2,
	'no-unsafe-optional-chaining': 2,
	'no-unused-vars': [ 2, {
		varsIgnorePattern: '^h$|^React$',
	}],
	'no-useless-call': 2,
	'no-useless-catch': 2,
	'no-var': 2,
	'no-void': 2,
	'object-curly-spacing': [ 2, 'always' ],
	'one-var': [ 2, 'never' ],
	'operator-linebreak': [ 2, 'after' ],
	'padded-blocks': [ 2, 'never' ],
	'prefer-const': 2,
	'quote-props': [ 2, 'consistent-as-needed' ],
	'quotes': [ 2, 'single', {
		allowTemplateLiterals: true,
	}],
	'require-await': 2,
	'semi': [ 2, 'never' ],
	'semi-spacing': [ 2, {
		after: true,
		before: false,
	}],
	'space-before-blocks': [ 2, 'always' ],
	'space-before-function-paren': [ 2, {
		anonymous: 'never',
		asyncArrow: 'always',
		named: 'never',
	}],
	'space-in-parens': [ 2, 'never' ],
	'space-infix-ops': 2,
	'space-unary-ops': [ 2, {
		nonwords: false,
		words: true,
	}],
	'spaced-comment': [ 2, 'always' ],
	'template-curly-spacing': [ 2, 'always' ],
	'use-isnan': 2,
	'valid-jsdoc': [ 2, {
		prefer: {
			return: 'returns',
		},
		requireParamDescription: false,
		requireReturn: false,
		requireReturnDescription: false,
	}],
	'valid-typeof': 2,
	'wrap-iife': 2,
	'wrap-regex': 2,
}