module.exports = {
	'import/named': 2,
	'import/default': 2,
	'import/no-absolute-path': 2,
	'import/no-dynamic-require': 2,
	'import/no-webpack-loader-syntax': 2,
	'import/no-self-import': 2,
	'import/no-cycle': 2,
	'import/no-useless-path-segments': 2,
	'import/no-named-as-default': 2,
	'import/no-named-as-default-member': 2,
	'import/no-extraneous-dependencies': 2,
	'import/no-mutable-exports': 2,
	'import/no-unused-modules': 2,
	'import/no-amd': 2,
	'import/no-duplicates': 2,
	'import/no-named-default': 2,
	'import/export': 2,
	'import/newline-after-import': 2,
}