module.exports = {
	parserOptions: {
		ecmaVersion: 2021,
		sourceType: 'module',
		ecmaFeatures: {
			jsx: true,
		},
	},
	plugins: [ 'react', 'react-hooks', 'import', 'unicorn' ],
	env: {
		browser: true,
		node: true,
		commonjs: true,
		mocha: true,
		es6: true,
	},
	rules: {
		'no-cond-assign': [ 2, 'always' ],
		'no-constant-condition': 2,
		'no-dupe-args': 2,
		'no-dupe-keys': 2,
		'no-duplicate-case': 2,
		'no-empty-character-class': 2,
		'no-extra-boolean-cast': 2,
		'no-extra-semi': 2,
		'no-func-assign': 2,
		'no-invalid-regexp': 2,
		'no-irregular-whitespace': 2,
		'no-unsafe-negation': 2,
		'no-obj-calls': 2,
		'no-unreachable': 2,
		'no-dupe-else-if': 2,
		'no-unsafe-optional-chaining': 2,
		'no-array-constructor': 2,
		'no-lonely-if': 2,
		'no-extra-parens': [ 2, 'functions' ],
		'no-unexpected-multiline': 2,
		'no-class-assign': 2,
		'no-const-assign': 2,
		'no-this-before-super': 2,
		'no-empty': [ 2, {
			allowEmptyCatch: true,
		}],
		'use-isnan': 2,
		'valid-typeof': 2,
		'eqeqeq': [ 2, 'always', {
			null: 'ignore',
		}],
		'new-parens': 2,
		'keyword-spacing': 2,
		'wrap-regex': 2,
		'arrow-spacing': [ 2, {
			before: true,
			after: true,
		}],
		'constructor-super': 2,
		'prefer-const': 2,
		'valid-jsdoc': [
			2,
			{
				prefer: { return: 'returns' },
				requireParamDescription: false,
				requireReturnDescription: false,
				requireReturn: false,
			},
		],
		'dot-location': [ 2, 'property' ],
		'wrap-iife': 2,
		'array-bracket-spacing': [ 2, 'always', {
			objectsInArrays: false,
			arraysInArrays: false,
		}],
		'brace-style': [ 2, '1tbs', {
			allowSingleLine: true,
		}],
		'camelcase': [ 2, {
			properties: 'never',
		}],
		'comma-spacing': [ 2, {
			before: false,
			after: true,
		}],
		'comma-style': [ 2, 'last' ],
		'comma-dangle': [ 2, {
			arrays: 'only-multiline',
			objects: 'only-multiline',
			imports: 'only-multiline',
			exports: 'only-multiline',
			functions: 'only-multiline',
		}],
		'indent': [ 2, 'tab', {
			SwitchCase: 1,
			CallExpression: {
				arguments: 'off',
			},
		}],
		'key-spacing': [ 2, {
			beforeColon: false,
			afterColon: true,
		}],
		'eol-last': [ 2, 'never' ],
		'no-mixed-spaces-and-tabs': 2,
		'no-multiple-empty-lines': 2,
		'no-nested-ternary': 2,
		'no-trailing-spaces': 2,
		'one-var': [ 2, 'never' ],
		'quote-props': [ 2, 'consistent-as-needed' ],
		'padded-blocks': [ 2, 'never' ],
		'quotes': [ 2, 'single', {
			allowTemplateLiterals: true,
		}],
		'semi': [ 2, 'never' ],
		'semi-spacing': [ 2, {
			before: false,
			after: true,
		}],
		'space-before-blocks': [ 2, 'always' ],
		'space-before-function-paren': [ 2, {
			anonymous: 'never',
			named: 'never',
			asyncArrow: 'always',
		}],
		'space-in-parens': [ 2, 'never' ],
		'space-infix-ops': 2,
		'space-unary-ops': [ 2, {
			words: true,
			nonwords: false,
		}],
		'spaced-comment': [ 2, 'always' ],
		'generator-star-spacing': [ 2, {
			before: false,
		}],
		'computed-property-spacing': 2,
		'implicit-arrow-linebreak': 2,
		'object-curly-spacing': [ 2, 'always' ],
		'operator-linebreak': [ 2, 'after' ],
		'func-style': 2,
		'newline-per-chained-call': 2,
		'new-cap': 2,
		'no-var': 2,
		'no-labels': 2,
		'no-implicit-coercion': 2,
		'no-implied-eval': 2,
		'no-lone-blocks': 2,
		'no-multi-spaces': 2,
		'no-multi-str': 2,
		'no-global-assign': 2,
		'no-new-func': 2,
		'no-new-wrappers': 2,
		'no-proto': 2,
		'no-redeclare': 2,
		'no-script-url': 2,
		'no-self-compare': 2,
		'no-sequences': 2,
		'no-useless-call': 2,
		'no-void': 2,
		'no-undef-init': 2,
		'no-caller': 2,
		'no-eval': 2,
		'no-extend-native': 2,
		'no-fallthrough': 2,
		'no-octal': 2,
		'no-delete-var': 2,
		'no-undef': 2,
		'no-unused-vars': [ 2, {
			varsIgnorePattern: '^h$|^React$',
		}],
		'no-new-require': 2,
		'no-path-concat': 2,
		'no-constructor-return': 2,
		'func-call-spacing': 2,
		'no-unneeded-ternary': 2,
		'callback-return': 2,
		'no-new-object': 2,
		'handle-callback-err': 2,
		'no-useless-catch': 2,
		'no-floating-decimal': 2,
		'no-misleading-character-class': 2,
		'no-async-promise-executor': 2,
		'no-compare-neg-zero': 2,
		'lines-between-class-members': [ 2, 'always', {
			exceptAfterSingleLine: true,
		}],
		'getter-return': 2,
		'template-curly-spacing': [ 2, 'always' ],
		'arrow-parens': [ 2, 'always' ],
		'jsx-quotes': [ 2, 'prefer-double' ],
		'default-case-last': 2,
		'grouped-accessor-pairs': [ 2, 'getBeforeSet' ],
		'require-await': 2,
		'react/jsx-closing-bracket-location': 2,
		'react/jsx-closing-tag-location': 2,
		'react/jsx-curly-spacing': [ 2, {
			when: 'always',
			children: true,
		}],
		'react/jsx-equals-spacing': [ 2, 'never' ],
		'react/jsx-first-prop-new-line': 2,
		'react/jsx-no-comment-textnodes': 2,
		'react/jsx-no-duplicate-props': 2,
		'react/jsx-curly-brace-presence': [	2, {
			props: 'never',
			children: 'never',
		}],
		'react/jsx-pascal-case': [ 2, {
			allowAllCaps: true,
		}],
		'react/jsx-tag-spacing': 2,
		'react/jsx-uses-vars': 2,
		'react/jsx-no-target-blank': 2,
		'react-hooks/rules-of-hooks': 2,
		'react-hooks/exhaustive-deps': 0,
		'import/named': 2,
		'import/default': 2,
		'import/no-absolute-path': 2,
		'import/no-dynamic-require': 2,
		'import/no-webpack-loader-syntax': 2,
		'import/no-self-import': 2,
		'import/no-cycle': 2,
		'import/no-useless-path-segments': 2,
		'import/export': 2,
		'import/no-named-as-default': 2,
		'import/no-named-as-default-member': 2,
		'import/no-extraneous-dependencies': 2,
		'import/no-mutable-exports': 2,
		'import/no-unused-modules': 2,
		'import/no-amd': 2,
		'import/no-duplicates': 2,
		'import/newline-after-import': 2,
		'import/no-named-default': 2,
		'unicorn/consistent-destructuring': 2,
		'unicorn/error-message': 2,
		'unicorn/new-for-builtins': 2,
		'unicorn/prefer-spread': 2,
		'unicorn/prefer-includes': 2,
		'unicorn/prefer-date-now': 2,
		'unicorn/no-useless-undefined': 2,
		'unicorn/no-unused-properties': 2,
		'unicorn/prefer-array-flat': 2,
		'unicorn/prefer-default-parameters': 2,
		'unicorn/prefer-switch': 2,
		'unicorn/numeric-separators-style': 2,
		'unicorn/require-array-join-separator': 2,
		'unicorn/require-number-to-fixed-digits-argument': 2,
		'unicorn/prefer-prototype-methods': 2,
		'unicorn/prefer-object-has-own': 2,
		'unicorn/filename-case': [ 2, {
			cases: {
				camelCase: true,
				pascalCase: true,
			},
		}],
		'unicorn/prevent-abbreviations': [ 2, {
			extendDefaultReplacements: false,
			replacements: {
				conf: {
					config: true,
				},
				i: {
					index: true,
				},
				err: {
					error: true,
				},
				ev: {
					event: true,
				},
				evt: {
					event: true,
				},
				opt: {
					option: true,
				},
				opts: {
					options: true,
				},
				val: {
					value: true,
				},
			},
		}],
	},
}